name: gctree
channels:
- etetoolkit
- defaults
dependencies:
- biopython=1.68=np111py27_0
- cloog=0.18.0=0
- cycler=0.10.0=py27_0
- freetype=2.5.5=2
- gcc=4.8.5=8
- gmp=6.1.0=0
- isl=0.12.2=1
- libiconv=1.14=0
- libpng=1.6.30=1
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- lxml=3.8.0=py27_0
- matplotlib=1.5.1=np111py27_0
- mkl=2017.0.3=0
- mpc=1.0.3=0
- mpfr=3.1.5=0
- numpy=1.11.3=py27_0
- openssl=1.0.2l=0
- pandas=0.20.1=np111py27_0
- patsy=0.4.1=py27_0
- pip=9.0.1=py27_1
- pyparsing=2.2.0=py27_0
- pyqt=4.11.4=py27_4
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- qt=4.8.7=4
- readline=6.2=2
- scipy=0.19.0=np111py27_0
- scons=2.3.0=py27_0
- seaborn=0.8=py27_0
- setuptools=27.2.0=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- statsmodels=0.8.0=np111py27_0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- argtable2=2.13=0
- ete3=3.0.0b36=py_0
- ete3_external_apps=2.0.3=py27_0
- pip:
  - nestly==0.6.1
prefix: /Users/williamdewitt/Applications/miniconda2/envs/gctree

